<?php

/* @var $this yii\web\View */

$this->title = $model->title;
?>
<div class="site-index">

    <div class="body-content">
        <p dir="ltr" style="line-height:1.7999999999999998;text-indent: 35.45pt;text-align: justify;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Trang web n&agrave;y l&agrave; một nền tảng để thực hiện c&aacute;c t&iacute;nh to&aacute;n thiết kế điển h&igrave;nh kh&aacute;c nhau về kỹ thuật x&acirc;y dựng theo TCVN. Kết quả t&iacute;nh to&aacute;n l&agrave; một b&aacute;o c&aacute;o ho&agrave;n thiện được tr&igrave;nh b&agrave;y dưới dạng *.docx.</span></p>
        <p><br></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: center;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">LỜI GIỚI THIỆU</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-indent: 35.45pt;text-align: justify;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Hiện nay, trong b&ocirc;́i cảnh c&ocirc;ng ngh&ecirc;̣ th&ocirc;ng tin ngày càng phát tri&ecirc;̉n thì nhu c&acirc;̀u cu&ocirc;̣c s&ocirc;́ng cũng như vi&ecirc;̣c ứng dụng c&ocirc;ng ngh&ecirc;̣ th&ocirc;ng tin vào c&ocirc;ng vi&ecirc;̣c của con người cũng được phát tri&ecirc;̉n mạnh mẽ và ngày càng đa dạng hơn, đặc bi&ecirc;̣t trong lĩnh vực x&acirc;y dựng y&ecirc;u c&acirc;̀u c&aacute;c doanh nghiệp, c&aacute; nh&acirc;n phải trang bị cho bản th&acirc;n những phần mềm, c&ocirc;ng cụ t&iacute;nh to&aacute;n. Nắm bắt được v&acirc;́n đ&ecirc;̀ n&agrave;y, t&aacute;c giả đ&atilde; lập n&ecirc;n website:&nbsp;</span><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:#ffff00;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">titool.vn</span><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;nhằm phục vụ cho c&aacute;c bạn sinh vi&ecirc;n, kỹ sư x&acirc;y dựng&hellip;c&oacute; thể d&ecirc;̃ dàng thao tác và tính toán m&ocirc;̣t cách hi&ecirc;̣u quả, nhanh chóng. Một trong những mục ti&ecirc;u ch&iacute;nh của trang web n&agrave;y l&agrave; tr&igrave;nh b&agrave;y ho&agrave;n chỉnh một b&aacute;o c&aacute;o kỹ thuật về kết quả t&iacute;nh to&aacute;n dựa tr&ecirc;n số liệu đầu v&agrave;o của người d&ugrave;ng. C&aacute;c mẫu t&iacute;nh to&aacute;n thực hiện theo c&aacute;c t&igrave;nh huống thiết kế được quy định cụ thể bởi văn bản quy phạm kỹ thuật.&nbsp;</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-indent: 35.45pt;text-align: justify;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Lưu &yacute; rằng c&aacute;c mẫu t&iacute;nh to&aacute;n tr&ecirc;n trang web chỉ l&agrave; một c&ocirc;ng cụ số học để thuận tiện cho việc t&iacute;nh to&aacute;n thiết kế v&agrave; tr&igrave;nh b&agrave;y kết quả. Tất cả c&aacute;c quy định về t&iacute;nh to&aacute;n, k&iacute; hiệu, đơn vị, m&ocirc; tả, giải th&iacute;ch v&agrave; quy tr&igrave;nh &aacute;p dụng ch&uacute;ng cũng sẽ được t&igrave;m thấy trong c&aacute;c ti&ecirc;u chuẩn x&acirc;y dựng Việt Nam (TCVN) li&ecirc;n quan. B&ecirc;n cạnh đó lời nhắc ở trang nhập dữ liệu chỉ mang t&iacute;nh hướng dẫn và kh&ocirc;ng được ph&eacute;p sử dụng c&aacute;c mẫu t&iacute;nh to&aacute;n của trang web nếu bạn kh&ocirc;ng phải l&agrave; chuy&ecirc;n gia trong lĩnh vực x&acirc;y dựng v&agrave; chưa nghi&ecirc;n cứu c&aacute;c TCVN. Ch&uacute;ng t&ocirc;i từ chối mọi tr&aacute;ch nhiệm về c&aacute;c lỗi c&oacute; thể xảy ra trong c&aacute;c mẫu t&iacute;nh to&aacute;n. Mọi&nbsp;</span><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">bảng t&iacute;nh&nbsp;</span><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">hi&ecirc;̉n thị tr&ecirc;n trang web đều được thực hiện &ldquo;nguy&ecirc;n trạng&rdquo; theo hướng dẫn t&iacute;nh to&aacute;n của c&aacute;c TCVN. Người sử dụng đưa ra quyết định về khả năng &aacute;p dụng, tr&aacute;ch nhiệm của m&igrave;nh đối với c&aacute;c t&iacute;nh to&aacute;n.</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-indent: 35.45pt;text-align: justify;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Hiện tại, hầu hết c&aacute;c b&aacute;o c&aacute;o được sắp xếp ở định dạng&nbsp;</span><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:#ffff00;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">*.pdf v&agrave; *.docx</span><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">, sẽ đem lại sự tiện lợi cho người d&ugrave;ng đ&ecirc;̉ c&oacute; thể tiếp cận với bố cục cũng như biểu thức to&aacute;n học ở thuyết minh t&iacute;nh to&aacute;n. Đồng thời, định dạng tr&igrave;nh b&agrave;y n&agrave;y sẽ cho ph&eacute;p nhiều chuy&ecirc;n gia đ&aacute;nh gi&aacute; t&iacute;nh đ&uacute;ng đắn của c&aacute;c t&iacute;nh to&aacute;n. Từ đ&oacute; sẽ đảm bảo loại bỏ c&aacute;c sai s&oacute;t c&oacute; thể xảy ra, mạng lại c&aacute;c ph&eacute;p t&iacute;nh ch&iacute;nh x&aacute;c v&agrave; đ&aacute;ng tin cậy.</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-indent: 35.45pt;text-align: justify;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Mặc d&ugrave; trong qu&aacute; tr&igrave;nh thực hiện t&aacute;c giả đ&atilde; cố gắng tr&igrave;nh b&agrave;y đơn giản v&agrave; tối ưu nhất để người d&ugrave;ng dễ d&agrave;ng sử dụng nhưng kh&ocirc;ng th&ecirc;̉ tr&aacute;nh khỏi những sai s&oacute;t chủ quan. Rất mong sự g&oacute;p &yacute; của c&aacute;c chuy&ecirc;n gia, đồng nghiệp cho c&aacute;c t&aacute;c giả th&ocirc;ng qua e-mail:&nbsp;</span><a href="mailto:abc@gmail.com" style="text-decoration:none;"><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:#ffff00;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">abc@gmail.com</span></a><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;để website ho&agrave;n thiện hơn. Xin ch&acirc;n th&agrave;nh cảm ơn!</span></p>
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: right;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:13.999999999999998pt;font-family:'Times New Roman';color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">C&aacute;c t&aacute;c giả</span></p>
    </div>
</div>